require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/posts", type: :request do

  # let!(:user) { create(:user) }
  # let!(:board) { create(:board, 1, user_id: user.id) }
  # let!(:categories) { create_list(:category, 5, board_id: board.id) }

  subject(:category) do
    PostCategory.create!(title: 'a' * 5, description: 'a' * 500)
  end

  let(:valid_attributes) do
    {
      author: User.current_user,
      category: category,
      category_id: category.id,
      title: 'a' * 50,
      content: 'a' * 200,
      tag_ids: []
    }
  end
  let(:invalid_attributes) do
    { title: 'a' * 2, content: 'a' * 2 }
  end

  describe "GET /index" do
    before do
      login_user
    end

    it "renders a successful response" do
      Post.create! valid_attributes
      get posts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    before do
      login_user
    end

    it "renders a successful response" do
      post = Post.create! valid_attributes
      get post_url(id: post.id)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    before do
      login_user
    end

    it "renders a successful response" do
      get new_post_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    before do
      login_user
    end

    it "render a successful response" do
      post = Post.create! valid_attributes
      get edit_post_url(id: post.id)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    before do
      login_user
    end

    context "with valid parameters" do
      it "creates a new Post" do
        expect do
          post posts_url, params: { post: valid_attributes }
        end.to change(Post, :count).by(1)
      end

      it "redirects to the created post" do
        post posts_url, params: { post: valid_attributes }
        expect(response).to redirect_to(post_url(Post.last))
      end
    end

    # context "with invalid parameters" do
    #   it "does not create a new Post" do
    #     expect do
    #       sign_in user
    #       post posts_url, params: { post: invalid_attributes }
    #     end.to change(Post, :count).by(0)
    #   end

    #   it "renders a successful response (i.e. to display the 'new' template)" do
    #     sign_in user
    #     post posts_url, params: { post: invalid_attributes }
    #     expect(response).to be_successful
    #   end
    # end
  end

  describe "PATCH /update" do
    before do
      login_user
    end

    context "with valid parameters" do
      let(:new_attributes) do
        { title: 'b' * 50 }
      end

      it "updates the requested post" do
        post = Post.create! valid_attributes
        patch post_url(id: post.id), params: { post: new_attributes }
        post.reload
        expect(post.title).to eq('b' * 50)
      end

      it "redirects to the post" do
        post = Post.create! valid_attributes
        patch post_url(id: post.id), params: { post: new_attributes }
        post.reload
        expect(response).to redirect_to(post_url(id: post.id))
      end
    end

    # context "with invalid parameters" do
    #   it "renders a successful response (i.e. to display the 'edit' template)" do
    #     sign_in user
    #     post = Post.create! valid_attributes
    #     patch post_url(post), params: { post: invalid_attributes }
    #     expect(response).to be_successful
    #   end
    # end
  end

  describe "DELETE /destroy" do
    before do
      login_user
    end

    it "destroys the requested post" do
      post = Post.create! valid_attributes
      expect do
        delete post_url(id: post.id)
      end.to change(Post, :count).by(-1)
    end

    it "redirects to the posts list" do
      post = Post.create! valid_attributes
      delete post_url(id: post.id)
      expect(response).to redirect_to(posts_url)
    end
  end
end
