---
development:
  cloud_name: dxqcdoq3f
  api_key: '792263448562233'
  api_secret: b8MSGROvjs70_P1hPt6do8fRblo
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dxqcdoq3f
  api_key: '792263448562233'
  api_secret: b8MSGROvjs70_P1hPt6do8fRblo
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dxqcdoq3f
  api_key: '792263448562233'
  api_secret: b8MSGROvjs70_P1hPt6do8fRblo
  enhance_image_tag: true
  static_file_support: false
